# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Ayoma Wijethunga
tagline: Home Page
email: public@ayoma.me
author: Ayoma Wijethunga
description: >- # this means to ignore newlines until "baseurl:"
  Personal home page and profile of Ayoma Wijethunga, Senior Technical Lead at WSO2 Security and Compliance Team.
  The site summarizes Ayoma's external profile information, certifications, achievements and other contributions to
  the infosec community. 
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: BriskSec
github_username:  ayomawdb

google_analytics: UA-143606463-1

# Build settings
markdown: kramdown
plugins:
  - jekyll-seo-tag

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
